// IMPORTANT: You can't use `preset` and `transform` properties together
// https://kulshekhar.github.io/ts-jest/docs/getting-started/installation
// https://kulshekhar.github.io/ts-jest/docs/getting-started/presets

// https://bobbyhadz.com/blog/typescript-jest-cannot-use-import-statement-outside-module
// https://jestjs.io/docs/ecmascript-modules

// Basic Jest config generated by `npx ts-jest config:init` command
// const config = {
//     preset: 'ts-jest',
//     testEnvironment: 'node',
//   };

const config = {
	testEnvironment: "node",
	transform: {
		"^.+\\.ts?$": "ts-jest",
		// https://kulshekhar.github.io/ts-jest/docs/getting-started/options
	},
	transformIgnorePatterns: ["<rootDir>/node_modules/"],
}

export default config